// <auto-generated />
using BookWebApi.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BookWebApi.EntityFrameworkCore.Migrations
{
    [DbContext(typeof(WebApiBookDbContext))]
    partial class WebApiBookDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BookWebApi.EntityFrameworkCore.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BookId");

                    b.Property<string>("FirstName");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("LastName");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.ToTable("Authors");

                    b.HasData(
                        new { Id = 1, BookId = 2, FirstName = "Daniel", IsDeleted = false, LastName = "Howard" },
                        new { Id = 2, BookId = 2, FirstName = "Rose", IsDeleted = false, LastName = "Smith" }
                    );
                });

            modelBuilder.Entity("BookWebApi.EntityFrameworkCore.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Title");

                    b.Property<int>("YearOfPublish");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new { Id = 1, IsDeleted = false, Title = "The Mahabharata Secret", YearOfPublish = 2015 },
                        new { Id = 2, IsDeleted = false, Title = "The Alexander Secret: Book 1 of the Mahabharata Quest Series", YearOfPublish = 2011 },
                        new { Id = 3, IsDeleted = false, Title = "The Mini Sequel to The Alexander Secret: A Secret Revealed ", YearOfPublish = 2009 },
                        new { Id = 4, IsDeleted = false, Title = "The Secret of the Druids", YearOfPublish = 2019 }
                    );
                });

            modelBuilder.Entity("BookWebApi.EntityFrameworkCore.Models.Author", b =>
                {
                    b.HasOne("BookWebApi.EntityFrameworkCore.Models.Book", "Book")
                        .WithMany("Authors")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
